# Generated by Django 5.0.4 on 2024-06-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_special_offer',
            field=models.BooleanField(default=False),
        ),
    ]
