# Generated by Django 5.0.6 on 2024-06-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_menuitem_is_special_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='is_special_offer',
        ),
    ]
